version: "3"

services:
  backend:
    build: ./
    container_name: mymarket_container
    working_dir: /my_market
    command:
      - ./commands/start_server.sh
    ports:
      - 8008:8008
    volumes:
      - ./src:/my_market/src
      - ./commands:/my_market/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongodb:
    image: mongo:3
    container_name: mongo_db_container
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - mg_data:/data/db


  mongoadmin:
    image: mongo-express
    restart: always
    container_name: mongo_admin_container
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongodb


volumes:
  pg_data: { }
  pgadmin_data: { }
  mg_data: { }