version: "3"

services:
  backend:
    build: ./
    container_name: mymarket_container
    working_dir: /my_market
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - ./src:/my_market/src
      - ./commands:/my_market/commands
      - static_content:/my_market/static
      - media_content:/my_market/media
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongodb:
    image: mongo:3
    container_name: mongo_db_container
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - mg_data:/data/db


  mongoadmin:
    image: mongo-express
    restart: always
    container_name: mongo_admin_container
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongodb

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/my_market/src/static
      - media_content:/my_market/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend

  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - backend

  celerybeat:
    build: ./
    command:
      - ./commands/start_celery_beat.sh
    restart: always
    volumes:
      - ./src:/my_market
      - ./commands:/my_market/commands
    env_file:
      - .env
    depends_on:
      - redis
      - backend


  redisadmin:
    image: rediscommander/redis-commander:latest
    container_name: redisadmin
    hostname: redisadmin
    restart: always
    ports:
      - 8092:8081
    env_file:
      - .env
    depends_on:
      - redis

  celery-flower:
    build: ./
    command:
      - ./commands/start_celery_flower.sh
    restart: always
    volumes:
      - ./src:/my_market
      - ./commands:/my_market/commands
    ports:
      - 5556:5555
    env_file:
      - .env
    depends_on:
      - redis
      - backend

volumes:
  static_content: { }
  media_content: { }
  pg_data: { }
  pgadmin_data: { }
  mg_data: { }
