# Generated by Django 4.1.7 on 2023-04-05 08:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="end_day",
            field=models.DateField(default=datetime.date(2023, 4, 15)),
        ),
    ]
