# Generated by Django 4.1.7 on 2023-04-12 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0004_alter_tender_end_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="start_day",
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.AlterField(
            model_name="tender",
            name="end_day",
            field=models.DateField(default=datetime.date(2023, 4, 22)),
        ),
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "New"),
                    (1, "Published"),
                    (2, "Executed"),
                    (3, "Canceled"),
                ],
                default=0,
            ),
        ),
    ]
