# Generated by Django 4.1.7 on 2023-04-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("tenders", "0006_tender_tender_name_alter_tender_buyer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="start_day",
        ),
        migrations.AddField(
            model_name="request",
            name="tender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="tenders.tender",
            ),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="tender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_parameter",
                to="tenders.tender",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="accounts.sellerprofile",
            ),
        ),
    ]
