# Generated by Django 4.1.7 on 2023-04-13 17:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0009_remove_tender_minimum_required_rang_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="winner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tender",
            name="end_day",
            field=models.DateField(default=datetime.date(2023, 4, 23)),
        ),
    ]
