# Generated by Django 4.1.7 on 2023-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="rank",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
