# Generated by Django 4.1.7 on 2023-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="rang",
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
