# Generated by Django 4.1.7 on 2023-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0003_alter_order_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveIntegerField(choices=[(0, "New"), (1, "In work"), (2, "Executed")], default=0),
        ),
    ]
